usePermissionsWhitelist: false
lockpair: true
lockedChestsSuck: false
verbose: false
key: 280
keyDurability: 0
comboKey: 352
comboKeyDurability: 0
useKeyDurability: false
suckRange: 3
openMessage: true
useLimits: false
lockLimits:
    example: 10
    anotherexample: 20