name: SimpleChestLock
main: com.webkonsept.bukkit.simplechestlock.SimpleChestLock
version: 0.11
branch: stable
thread: http://forums.bukkit.org/threads/SimpleChestLock.17557/
website: http://minecraft.webkonsept.com/plugins/details/SimpleChestLock.html
location: http://minecraft.webkonsept.com/plugins/download/SimpleChestLock.jar
database: false
commands:
    sclreload: 
        description: Reloads the ChestLock settings file and locked items list
        usage: /<command> (takes no arguments)
    sclsave:
        description: Saves the chests file
        usage: /<command> (takes no arguments)
generators: [bukget]
categories: [ SEC, MECH ]
description: Gives players the ability to lock chests and other blocks.
maintainer: DemmyDemon
authors: [DemmyDemon]
conflicts: []
required: []
optional: [Permissions]
permissions:
    simplechestlock.*:
        description: Full access
        children:
            simplechestlock.command.*: true
            simplechestlock.ignoreowner: true
            simplechestlock.lock.*: true
            simplechestlock.lock: true
            simplechestlock.usecombo: true
    simplechestlock.command.*:
        description: Access to both commands
        children:
            simplechestlock.command.reload: true
            simplechestlock.command.save: true
    simplechestlock.command.reload:
        description: Access to /sclreload
        default: op
    simplechestlock.command.save:
        description: Access to /sclsave
        default: op
    simplechestlock.ignoreowner:
        description: Unlock any item, use any item.
        default: op
    simplechestlock.lock:
        description: Access to locking items
        default: op
    simplechestlock.usecombo:
        description: Access to locking with a combination lock
        default: op
    simplechestlock.lock.*:
        description: Lock any lockable item
        default: op
    simplechestlock.lock.Lockable_Name_Here:
        description: Gives permission to lock Lockable_Name_Here blocks
        default: op
engines:
    craftbukkit:
        min: 1000
        max: 1000


