name: SimpleChestLock
main: com.webkonsept.bukkit.simplechestlock.SimpleChestLock
version: 0.7
website: http://minecraft.webkonsept.com/plugins/details/SimpleChestLock.jar
location: http://minecraft.webkonsept.com/plugins/download/SimpleChestLock.jar
author: Fredrik Vold
database: false
bukget: true
thread: http://forums.bukkit.org/threads/SimpleChestLock.17557/
build:
    min: 935
    max: 953
categories:
    - SEC
    - MECH
description: Gives players the ability to lock chests
commands:
    sclreload: 
        description: Reloads the ChestLock settings file
        usage: /<command> (takes no arguments)
    sclsave:
        description: Saves the chests file
        usage: /<command> (takes no arguments)