name: SimpleChestLock
main: com.webkonsept.bukkit.simplechestlock.SCL
version: 0.13.1
branch: stable
thread: http://forums.bukkit.org/threads/SimpleChestLock.17557/
website: http://minecraft.webkonsept.com/plugins/details/SimpleChestLock.html
location: http://minecraft.webkonsept.com/plugins/download/SimpleChestLock.jar
database: false
commands:
    scl:
        description:  Interact with SimpleChestLock
        usage: /<command> [save|reload|status|as]
generators: [bukget]
categories: [ SEC, MECH ]
description: Gives players the ability to lock chests and other blocks.
maintainer: DemmyDemon
authors: [DemmyDemon]
conflicts: []
required: []
optional: []
softdepend: [MultiVerse,Multiverse-Core,MyWorlds,emericaWorlds,WormholeExtreme]
permissions:
    simplechestlock.*:
        description: Full access
        children:
            simplechestlock.command.*: true
            simplechestlock.ignoreowner: true
            simplechestlock.locktype.*: true
            simplechestlock.lock: true
            simplechestlock.usecombo: true
    simplechestlock.command.*:
        description: Access to both commands
        children:
            simplechestlock.command.reload: true
            simplechestlock.command.save: true
            simplechestlock.command.status: true
            simplechestlock.command.list: true
            simplechestlock.command.as: true
    simplechestlock.command.reload:
        description: Access to /scl reload
        default: op
    simplechestlock.command.save:
        description: Access to /scl save
        default: op
    simplechestlock.command.status:
        description: Access to /scl status
        default: op
    simplechestlock.command.list:
        description: Access to /scl list
        default: op
    simplechestlock.command.as:
        description: Access to /scl as <name>
        default: op
    simplechestlock.ignoreowner:
        description: Unlock any item, use any item.
        default: op
    simplechestlock.lock:
        description: Access to locking items
        default: op
    simplechestlock.usecombo:
        description: Access to locking with a combination lock
        default: op
    simplechestlock.locktype.*:
        description: Lock any lockable item
        default: op
    simplechestlock.locktype.Lockable_Name_Here:
        description: Gives permission to lock Lockable_Name_Here blocks
        default: false
engines:
    craftbukkit:
        min: 1597
        max: 1597


