name: SimpleChestLock
main: com.webkonsept.bukkit.simplechestlock.SimpleChestLock
version: 0.5
website: http://minecraft.webkonsept.com/
author: Fredrik Vold
database: false
description: >
        Gives players the ability to lock chests
commands:
    sclreload:
        aliases: 
        description: Reloads the ChestLock settings file
        usage: /<command> (takes no arguments)
    sclsave:
        aliases:
        description: Saves the chests file
        usage: /<command> (takes no arguments)